version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  tori:
    image: us.icr.io/sdlc/sdlc-core-engine   

    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        WATSON_API_KEY: ${WATSON_API_KEY}
        WATSON_PROJECT_ID: ${WATSON_PROJECT_ID}
        IBM_WATSON_URL: ${IBM_WATSON_URL}
        SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
        SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
        SLACK_NOTIFICATION_CHANNEL: ${SLACK_NOTIFICATION_CHANNEL}
        TEAMS_WEBHOOK_URL: ${TEAMS_WEBHOOK_URL}
          
    depends_on:
        postgres:
            condition: service_healthy
    ports:
      - "8000:8000"  
